Add source cmd

diff --git a/.github/actions/workflow-queue-scan/action.yaml b/.github/actions/workflow-queue-scan/action.yaml
--- a/.github/actions/workflow-queue-scan/action.yaml
+++ b/.github/actions/workflow-queue-scan/action.yaml
@@ -10,24 +10,35 @@ runs:
     - name: Install GNU tools
       shell: sh
       run: |
+        prerequisites=""
         if ! which tar >/dev/null 2>&1 || tar --help >/dev/null 2>&1 | grep -q "BusyBox"; then
-          echo "Valud GNU tar not found. Installing..."
+          echo "Valid GNU tar command not found."
+          prerequisites="tar"
+        fi
+
+        #if ! which source >/dev/null 2>&1; then
+        #  echo "source command not found."
+        #  prerequisites="${prerequisites} source"
+        #fi
+
+        for pkg in $prerequisites ; do
+          echo "Installing ${pkg}..."
 
           if which apk >/dev/null 2>&1; then
-            apk add --no-cache tar
+            apk add --no-cache $pkg
           elif which apt-get >/dev/null 2>&1; then
-            apt-get install -y tar
+            apt-get install -y $pkg
           elif which dnf >/dev/null 2>&1; then
-            dnf install -y tar
+            dnf install -y $pkg
           elif which yum >/dev/null 2>&1; then
-            yum install -y tar
+            yum install -y $pkg
           else
-            echo "Unknown package manager. Could not install tar."
+            echo "Unknown package manager. Could not install ${pkg}."
             exit 1
           fi
-        else
-          echo "Valid GNU tar is already installed."
-        fi
+
+          echo "Installation successful."
+        done
 
     - name: Generate dependency hash
       id: generate-hash
@@ -50,7 +61,7 @@ runs:
       shell: sh
       run: |
         python -m venv .venv
-        source .venv/bin/activate
+        . .venv/bin/activate
         pip install --no-cache-dir -r "${GITHUB_ACTION_PATH}/requirements.txt"
 
     - name: Run script
@@ -58,5 +69,5 @@ runs:
       env: 
         GITHUB_TOKEN: ${{ inputs.github_token }}
       run: |
-        source .venv/bin/activate
+        . .venv/bin/activate
         python "${GITHUB_ACTION_PATH}/main.py"
