Add helper action for hash info generation

diff --git a/.github/actions/workflow-queue-scan/action.yaml b/.github/actions/workflow-queue-scan/action.yaml
--- a/.github/actions/workflow-queue-scan/action.yaml
+++ b/.github/actions/workflow-queue-scan/action.yaml
@@ -7,57 +7,60 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Install GNU tools
-      shell: sh
-      run: |
-        prerequisites=""
-        if ! which tar >/dev/null 2>&1 || tar --help >/dev/null 2>&1 | grep -q "BusyBox"; then
-          echo "Valid GNU tar command not found."
-          prerequisites="tar"
-        fi
-
-        #if ! which source >/dev/null 2>&1; then
-        #  echo "source command not found."
-        #  prerequisites="${prerequisites} source"
-        #fi
-
-        for pkg in $prerequisites ; do
-          echo "Installing ${pkg}..."
-
-          if which apk >/dev/null 2>&1; then
-            apk add --no-cache $pkg
-          elif which apt-get >/dev/null 2>&1; then
-            apt-get install -y $pkg
-          elif which dnf >/dev/null 2>&1; then
-            dnf install -y $pkg
-          elif which yum >/dev/null 2>&1; then
-            yum install -y $pkg
-          else
-            echo "Unknown package manager. Could not install ${pkg}."
-            exit 1
-          fi
-
-          echo "Installation successful."
-        done
-
-    - name: Generate dependency hash
-      id: generate-hash
-      shell: sh
-      run: |
-        DISTRO_ID=$(grep -E '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
-        echo "distro-id=${DISTRO_ID}" >> $GITHUB_OUTPUT
-
-        HASH=$(md5sum "${GITHUB_ACTION_PATH}/requirements.txt" | awk '{ print $1 }')
-        echo "hash=${HASH}" >> $GITHUB_OUTPUT
+#    - name: Install GNU tools
+#      shell: sh
+#      run: |
+#        prerequisites=""
+#        if ! which tar >/dev/null 2>&1 || tar --help >/dev/null 2>&1 | grep -q "BusyBox"; then
+#          echo "Valid GNU tar command not found."
+#          prerequisites="tar"
+#        fi
+#
+#        #if ! which source >/dev/null 2>&1; then
+#        #  echo "source command not found."
+#        #  prerequisites="${prerequisites} source"
+#        #fi
+#
+#        for pkg in $prerequisites ; do
+#          echo "Installing ${pkg}..."
+#
+#          if which apk >/dev/null 2>&1; then
+#            apk add --no-cache $pkg
+#          elif which apt-get >/dev/null 2>&1; then
+#            apt-get install -y $pkg
+#          elif which dnf >/dev/null 2>&1; then
+#            dnf install -y $pkg
+#          elif which yum >/dev/null 2>&1; then
+#            yum install -y $pkg
+#          else
+#            echo "Unknown package manager. Could not install ${pkg}."
+#            exit 1
+#          fi
+#
+#          echo "Installation successful."
+#        done
+#
+#    - name: Generate dependency hash
+#      id: generate-hash
+#      shell: sh
+#      run: |
+#        DISTRO_ID=$(grep -E '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
+#        echo "distro-id=${DISTRO_ID}" >> $GITHUB_OUTPUT
+#
+#        HASH=$(md5sum "${GITHUB_ACTION_PATH}/requirements.txt" | awk '{ print $1 }')
+#        echo "hash=${HASH}" >> $GITHUB_OUTPUT
+    - name: Prepare container environment
+      id: prep-env
+      uses: ./.github/actions/prep-container-env
 
     - name: Cache virtual environment
       id: cache-venv
       uses: actions/cache@v5
       with:
         path: .venv
-        key: workflow-scan-${{ steps.generate-hash.outputs.distro-id }}-${{ steps.generate-hash.outputs.hash }}
+        key: workflow-scan-${{ steps.prep-env.outputs.distro-id }}-${{ steps.prep-env.outputs.hash }}
         restore-keys: |
-          workflow-scan-${{ steps.generate-hash.outputs.distro-id }}-
+          workflow-scan-${{ steps.prep-env.outputs.distro-id }}-
 
     - name: Install dependencies
       if: steps.cache-venv.outputs.cache-hit != 'true'
